service: express-app-lambda

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: index.handler
    events:
      - http: GET /

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true;
